In [1]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler, MaxAbsScaler
import numpy as np

# Create a simple dataset
data = np.array([[1], [2], [3], [4], [5], [6], [7], [8], [9], [10]]).astype(float)

In [2]:
data

array([[ 1.],
       [ 2.],
       [ 3.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 7.],
       [ 8.],
       [ 9.],
       [10.]])

In [3]:
# Initialize scalers
standard_scaler = StandardScaler()
min_max_scaler = MinMaxScaler()
robust_scaler = RobustScaler()
max_abs_scaler = MaxAbsScaler()

In [4]:
# Scale the data using different scalers
scaled_standard = standard_scaler.fit_transform(data)
scaled_min_max = min_max_scaler.fit_transform(data)
scaled_robust = robust_scaler.fit_transform(data)
scaled_max_abs = max_abs_scaler.fit_transform(data)

In [5]:
# Show the original and scaled data
scaled_data = {
    "Original": data.flatten(),
    "StandardScaler": scaled_standard.flatten(),
    "MinMaxScaler": scaled_min_max.flatten(),
    "RobustScaler": scaled_robust.flatten(),
    "MaxAbsScaler": scaled_max_abs.flatten()
}

In [7]:
scaled_data

{'Original': array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 'StandardScaler': array([-1.5666989 , -1.21854359, -0.87038828, -0.52223297, -0.17407766,
         0.17407766,  0.52223297,  0.87038828,  1.21854359,  1.5666989 ]),
 'MinMaxScaler': array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
        0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ]),
 'RobustScaler': array([-1.        , -0.77777778, -0.55555556, -0.33333333, -0.11111111,
         0.11111111,  0.33333333,  0.55555556,  0.77777778,  1.        ]),
 'MaxAbsScaler': array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])}

In [9]:
scaled_standard.mean()

-6.661338147750939e-17

In [10]:
scaled_standard.std()

1.0

In [14]:
# StandardScaler
(data - data.mean())/data.std()

array([[-1.5666989 ],
       [-1.21854359],
       [-0.87038828],
       [-0.52223297],
       [-0.17407766],
       [ 0.17407766],
       [ 0.52223297],
       [ 0.87038828],
       [ 1.21854359],
       [ 1.5666989 ]])

In [16]:
# MinMax scaler
(data - data.min())/(data.max() - data.min())

array([[0.        ],
       [0.11111111],
       [0.22222222],
       [0.33333333],
       [0.44444444],
       [0.55555556],
       [0.66666667],
       [0.77777778],
       [0.88888889],
       [1.        ]])